version: '3.9'
services:
  frontend:
    image: devandresilva/frontend:latest
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - minha-rede
    depends_on:
      - backend
    command: >
      sh -c "git pull origin main && nginx -g 'daemon off;'"

  backend:
    image: devandresilva/backend:latest
    ports:
      - "3000:3000"
    networks:
      - minha-rede
    depends_on:
      - db
    container_name: backend
    command: >
      /bin/sh -c "
      git pull &&
      node index.js"

  db:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: pokemon
      POSTGRES_USER: pokemon
      POSTGRES_DB: pokemons

    networks:
      - minha-rede
    container_name: db
    volumes:
      - ./pgdata:/var/lib/postgres

networks:
  minha-rede:
